### ISSUE TITLE
Server response

### ISSUE THREAD

**Issue by knownasilya** [funtusov/ember-cli-form-data#2]
So from the readme it's obvious what gets set on the attribute, but what should the server respond with to send the file to the browser? Should there be a second attribute for the url (or image base64 data)?

**Comment by funtusov** [comment]
Yes, the easiest way to use it is to have a url field. And since the return from a post/put request expected by Ember.Data is a full object representation, it will be set automatically if the API is following Ember's conventions. Let me know if you have issues, I can lend a hand if the server is in ruby  :)
